{
 "bad": false,
 "new_version": "13.0.19.0",
 "new_version_attempts": {
  "10.0.26.0": 2,
  "10.0.26.1": 1,
  "11.0.10.0": 1,
  "11.0.10.1": 1,
  "11.1.5.0": 1,
  "11.1.5.1": 1,
  "11.1.5.2": 1,
  "12.0.16.0": 1,
  "12.0.16.1": 1,
  "12.1.14.0": 1,
  "12.2.72.0": 0,
  "13.0.19.0": 2
 },
 "new_version_errors": {
  "13.0.19.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/13061383347\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 225, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 251, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 254, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '13.0.19.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/FFmpeg/nv-codec-headers/releases/download/n{{ version }}/nv-codec-headers-{{ version }}.tar.gz'\n\n"
 }
}