{
 "bad": false,
 "new_version": "6.25.0",
 "new_version_attempts": {
  "5.42.2": 3,
  "5.42.3": 1,
  "5.43.0": 3,
  "5.43.1": 7,
  "5.43.2": 4,
  "5.43.3": 3,
  "6.22.0": 3,
  "6.23.0": 1,
  "6.23.0-weekly.231": 1,
  "6.24.0": 73,
  "6.24.0-weekly.232": 4,
  "6.24.1": 7,
  "6.25.0": 20
 },
 "new_version_errors": {
  "5.42.2": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '5.42.2' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n",
  "5.42.3": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '5.42.3' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n",
  "5.43.0": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '5.43.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n",
  "5.43.1": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '5.43.1' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n",
  "5.43.2": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '5.43.2' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n",
  "5.43.3": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/11947194393\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name loki-logcli --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '5.43.3' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\"",
  "6.22.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12079797316\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name loki-logcli --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6.22.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\"",
  "6.23.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12206520780\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name loki-logcli --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6.23.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\"",
  "6.23.0-weekly.231": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12188690610\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name loki-logcli --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6.23.0-weekly.231' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\"",
  "6.24.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12789437961\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 225, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 251, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 218, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6.24.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\n",
  "6.24.0-weekly.232": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12349432477\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name loki-logcli --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6.24.0-weekly.232' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\"",
  "6.24.1": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12836074924\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 225, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 251, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 254, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6.24.1' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\n",
  "6.25.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12909749886\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 225, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 251, in run_migration_local\n    data[\"migrate_return_value\"] = migrator.migrate(\n                                   ^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 254, in migrate\n    raise VersionMigrationError(\nconda_forge_tick.migrators.version.VersionMigrationError: The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '6.25.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/grafana/loki/archive/v{{ version }}.tar.gz'\n\n"
 }
}