{
 "bad": false,
 "new_version": "2024.12.0",
 "new_version_attempts": {
  "2024.11.0": 3,
  "2024.11.1": 3
 },
 "new_version_errors": {
  "2024.11.0": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/11946261354\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name pyfes --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2024.11.0' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/CNES/aviso-fes/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz'\n\"",
  "2024.11.1": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/11973626742\">bot CI job</a>): main:\nError running 'conda-forge-tick-container migrate-feedstock --feedstock-name pyfes --default-branch main --existing-feedstock-node-attrs - --log-level info --kwargs {\n \"hash_type\": \"sha256\"\n}' in container - error VersionMigrationError raised:\n\"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '2024.11.1' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://github.com/CNES/aviso-fes/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz'\n\""
 }
}