{
 "bad": false,
 "pre_pr_migrator_attempts": {
  "noarch_python_min": 6
 },
 "pre_pr_migrator_status": {
  "noarch_python_min": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12932508072\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 104, in _run_bot_task\n    data = func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 216, in _rerender_feedstock\n    msg = rerender_local(fs_dir, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py\", line 255, in rerender_local\n    raise RuntimeError(f\"Failed to rerender.\noutput: {ret.stdout}\n\")\nRuntimeError: Failed to rerender.\noutput: Adding in variants from internal_defaults\nAdding in variants from /tmp/tmptzrca25s/conda-smithy/conda_build_config.yaml\nAdding in variants from argument_variants\nsubpackages_about [('bech32', {'home': 'https://github.com/fiatjaf/bech32', 'summary': 'Reference implementation for Bech32 and segwit addresses.', 'license': 'MIT', 'license_file': 'LICENSE.txt'})]\nINFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2025.01.23.13.47.17\nINFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmptzrca25s/conda-smithy\nINFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped\nINFO:conda_smithy.configure_feedstock:README rendering is skipped\nWARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.\nWARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.\nWARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 767, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 610, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 613, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2913, in main\n    render_readme(env, config, forge_dir, render_info)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2150, in render_readme\n    forge_config[\"maintainers\"] = [\n                                  ^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2151, in <listcomp>\n    (name, get_maintainer_url(name)) for name in maintainers\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2039, in get_maintainer_url\n    org, team_name = user_or_team.split(\"/\")\n    ^^^^^^^^^^^^^^\nValueError: too many values to unpack (expected 2)\n\n\n"
 }
}