{
  "_feedstock_status": {
    "aruco": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/aruco-feedstock/pull/17",
      "pre_pr_migrator_status": ""
    },
    "bgslibrary": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/bgslibrary-feedstock/pull/11",
      "pre_pr_migrator_status": ""
    },
    "bipedal-locomotion-framework": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/103",
      "pre_pr_migrator_status": ""
    },
    "ergocub-software": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/ergocub-software-feedstock",
      "pre_pr_migrator_status": ""
    },
    "gazebo-yarp-plugins": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/13215546592\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 104, in _run_bot_task\n    data = func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/__main__.py\", line 216, in _rerender_feedstock\n    msg = rerender_local(fs_dir, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py\", line 255, in rerender_local\n    raise RuntimeError(f\"Failed to rerender.\noutput: {ret.stdout}\n\")\nRuntimeError: Failed to rerender.\noutput: Traceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 767, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 610, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 613, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2858, in main\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2671, in get_cached_cfp_file_path\n    current_pinning_version = get_most_recent_version(\n                              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2544, in get_most_recent_version\n    request.raise_for_status()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 524 Server Error:  for url: https://api.anaconda.org/package/conda-forge/conda-forge-pinning\n\n\n"
    },
    "icub-main": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "unstable",
      "pr_url": "https://github.com/conda-forge/icub-main-feedstock/pull/16",
      "pre_pr_migrator_status": ""
    },
    "imgui-bundle": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/imgui-bundle-feedstock",
      "pre_pr_migrator_status": ""
    },
    "imp": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/imp-feedstock",
      "pre_pr_migrator_status": ""
    },
    "libcaer": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/libcaer-feedstock",
      "pre_pr_migrator_status": ""
    },
    "nvidia-dali-python": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/nvidia-dali-python-feedstock",
      "pre_pr_migrator_status": ""
    },
    "pycontour": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/pycontour-feedstock",
      "pre_pr_migrator_status": ""
    },
    "robotraconteur_companion": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/robotraconteur_companion-feedstock",
      "pre_pr_migrator_status": ""
    },
    "visp": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": ""
    },
    "yarp": {
      "immediate_children": [
        "bipedal-locomotion-framework",
        "ergocub-software",
        "gazebo-yarp-plugins",
        "icub-main"
      ],
      "num_descendants": 4,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/yarp-feedstock",
      "pre_pr_migrator_status": ""
    }
  },
  "awaiting-parents": [
    "visp"
  ],
  "awaiting-pr": [],
  "bot-error": [
    "gazebo-yarp-plugins"
  ],
  "done": [
    "yarp",
    "ergocub-software",
    "robotraconteur_companion",
    "pycontour",
    "nvidia-dali-python",
    "libcaer",
    "imp",
    "imgui-bundle"
  ],
  "in-pr": [
    "icub-main",
    "bipedal-locomotion-framework",
    "bgslibrary",
    "aruco"
  ],
  "not-solvable": []
}